CREATE TABLE games (
    id UUID PRIMARY KEY,
    room_code TEXT NOT NULL,
    completion_kind TEXT NOT NULL,
    rounds_played INTEGER NOT NULL,
    player_count INTEGER NOT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT games_completion_kind_check CHECK (completion_kind IN ('normal', 'forfeit')),
    CONSTRAINT games_rounds_positive CHECK (rounds_played > 0),
    CONSTRAINT games_player_count_check CHECK (player_count BETWEEN 2 AND 4)
);

CREATE INDEX games_completed_at_idx ON games (completed_at DESC);

CREATE TABLE game_player_statistics (
    game_id UUID NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    placement INTEGER NOT NULL,
    won BOOLEAN NOT NULL,
    forfeited BOOLEAN NOT NULL,
    total_points INTEGER NOT NULL,
    rounds_played INTEGER NOT NULL,
    rounds_won INTEGER NOT NULL,
    same_suit_wins INTEGER NOT NULL,
    six_pairs_wins INTEGER NOT NULL,
    turns_taken INTEGER NOT NULL,
    cards_drawn_from_deck INTEGER NOT NULL,
    cards_drawn_from_discard INTEGER NOT NULL,
    cards_discarded INTEGER NOT NULL,
    cards_played INTEGER NOT NULL,
    compositions_created INTEGER NOT NULL,
    sets_created INTEGER NOT NULL,
    runs_created INTEGER NOT NULL,
    additions_done INTEGER NOT NULL,
    compositions_completed INTEGER NOT NULL,
    sets_completed INTEGER NOT NULL,
    runs_completed INTEGER NOT NULL,
    jokers_played INTEGER NOT NULL,
    jokers_reclaimed INTEGER NOT NULL,
    cards_remaining INTEGER NOT NULL,
    hand_points INTEGER NOT NULL,
    penalty_points INTEGER NOT NULL,
    points_inflicted INTEGER NOT NULL,
    largest_round_penalty INTEGER NOT NULL,
    largest_round_points_inflicted INTEGER NOT NULL,
    most_cards_remaining INTEGER NOT NULL,
    rounds_opened INTEGER NOT NULL,
    fastest_opening_turn INTEGER NOT NULL,
    starting_round_win_streak INTEGER NOT NULL,
    ending_round_win_streak INTEGER NOT NULL,
    longest_round_win_streak INTEGER NOT NULL,
    PRIMARY KEY (game_id, user_id),
    CONSTRAINT game_player_statistics_placement_positive CHECK (placement > 0)
);

CREATE INDEX game_player_statistics_user_id_idx
    ON game_player_statistics (user_id, game_id);

-- Cached lifetime totals keep profiles and leaderboards cheap. The per-game
-- rows above remain the auditable source from which this row can be rebuilt.
CREATE TABLE player_statistics (
    user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    games_played BIGINT NOT NULL DEFAULT 0,
    games_won BIGINT NOT NULL DEFAULT 0,
    total_placement BIGINT NOT NULL DEFAULT 0,
    rounds_played BIGINT NOT NULL DEFAULT 0,
    rounds_won BIGINT NOT NULL DEFAULT 0,
    same_suit_wins BIGINT NOT NULL DEFAULT 0,
    six_pairs_wins BIGINT NOT NULL DEFAULT 0,
    forfeits BIGINT NOT NULL DEFAULT 0,
    turns_taken BIGINT NOT NULL DEFAULT 0,
    cards_drawn_from_deck BIGINT NOT NULL DEFAULT 0,
    cards_drawn_from_discard BIGINT NOT NULL DEFAULT 0,
    cards_discarded BIGINT NOT NULL DEFAULT 0,
    cards_played BIGINT NOT NULL DEFAULT 0,
    compositions_created BIGINT NOT NULL DEFAULT 0,
    sets_created BIGINT NOT NULL DEFAULT 0,
    runs_created BIGINT NOT NULL DEFAULT 0,
    additions_done BIGINT NOT NULL DEFAULT 0,
    compositions_completed BIGINT NOT NULL DEFAULT 0,
    sets_completed BIGINT NOT NULL DEFAULT 0,
    runs_completed BIGINT NOT NULL DEFAULT 0,
    jokers_played BIGINT NOT NULL DEFAULT 0,
    jokers_reclaimed BIGINT NOT NULL DEFAULT 0,
    cards_remaining BIGINT NOT NULL DEFAULT 0,
    hand_points BIGINT NOT NULL DEFAULT 0,
    penalty_points BIGINT NOT NULL DEFAULT 0,
    points_inflicted BIGINT NOT NULL DEFAULT 0,
    largest_round_penalty INTEGER NOT NULL DEFAULT 0,
    largest_round_points_inflicted INTEGER NOT NULL DEFAULT 0,
    most_cards_remaining INTEGER NOT NULL DEFAULT 0,
    rounds_opened BIGINT NOT NULL DEFAULT 0,
    fastest_opening_turn INTEGER NOT NULL DEFAULT 0,
    current_game_win_streak INTEGER NOT NULL DEFAULT 0,
    longest_game_win_streak INTEGER NOT NULL DEFAULT 0,
    current_round_win_streak INTEGER NOT NULL DEFAULT 0,
    longest_round_win_streak INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
