/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedDevUiRouteImport } from './routes/_protected/dev-ui'
import { Route as ProtectedLeaderboardRouteImport } from './routes/_protected/leaderboard'
import { Route as ProtectedPlayersPlayerIdRouteImport } from './routes/_protected/players.$playerId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDevUiRoute = ProtectedDevUiRouteImport.update({
  id: '/dev-ui',
  path: '/dev-ui',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedLeaderboardRoute = ProtectedLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPlayersPlayerIdRoute =
  ProtectedPlayersPlayerIdRouteImport.update({
    id: '/players/$playerId',
    path: '/players/$playerId',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/dev-ui': typeof ProtectedDevUiRoute
  '/leaderboard': typeof ProtectedLeaderboardRoute
  '/players/$playerId': typeof ProtectedPlayersPlayerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedIndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/dev-ui': typeof ProtectedDevUiRoute
  '/leaderboard': typeof ProtectedLeaderboardRoute
  '/players/$playerId': typeof ProtectedPlayersPlayerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_protected/dev-ui': typeof ProtectedDevUiRoute
  '/_protected/leaderboard': typeof ProtectedLeaderboardRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/players/$playerId': typeof ProtectedPlayersPlayerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/dev-ui'
    | '/leaderboard'
    | '/players/$playerId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sign-in' | '/dev-ui' | '/leaderboard' | '/players/$playerId'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/_auth/sign-in'
    | '/_protected/dev-ui'
    | '/_protected/leaderboard'
    | '/_protected/'
    | '/_protected/players/$playerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dev-ui': {
      id: '/_protected/dev-ui'
      path: '/dev-ui'
      fullPath: '/dev-ui'
      preLoaderRoute: typeof ProtectedDevUiRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/leaderboard': {
      id: '/_protected/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof ProtectedLeaderboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/players/$playerId': {
      id: '/_protected/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof ProtectedPlayersPlayerIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedRouteChildren {
  ProtectedDevUiRoute: typeof ProtectedDevUiRoute
  ProtectedLeaderboardRoute: typeof ProtectedLeaderboardRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedPlayersPlayerIdRoute: typeof ProtectedPlayersPlayerIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDevUiRoute: ProtectedDevUiRoute,
  ProtectedLeaderboardRoute: ProtectedLeaderboardRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedPlayersPlayerIdRoute: ProtectedPlayersPlayerIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
