// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: game_bug_reports.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeGameBugReport = `-- name: CompleteGameBugReport :one
UPDATE game_bug_reports
SET completed_at = NOW()
WHERE id = $1::uuid
  AND completed_at IS NULL
RETURNING id::text AS completed_id
`

func (q *Queries) CompleteGameBugReport(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, completeGameBugReport, id)
	var completed_id string
	err := row.Scan(&completed_id)
	return completed_id, err
}

const countGameBugReports = `-- name: CountGameBugReports :one
SELECT COUNT(*) FROM game_bug_reports WHERE completed_at IS NULL
`

func (q *Queries) CountGameBugReports(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countGameBugReports)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGameBugReport = `-- name: CreateGameBugReport :one
INSERT INTO game_bug_reports (
    id,
    room_code,
    reporter_player_id,
    reporter_user_id,
    description,
    game_state,
    round,
    turn,
    requested_abort,
    created_at
)
VALUES (
    $1::uuid,
    $2,
    $3,
    $4::uuid,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING
    id::text AS id,
    room_code,
    reporter_player_id,
    reporter_user_id,
    description,
    game_state,
    round,
    turn,
    requested_abort,
    created_at
`

type CreateGameBugReportParams struct {
	ID               pgtype.UUID        `json:"id"`
	RoomCode         string             `json:"room_code"`
	ReporterPlayerID string             `json:"reporter_player_id"`
	ReporterUserID   pgtype.UUID        `json:"reporter_user_id"`
	Description      string             `json:"description"`
	GameState        []byte             `json:"game_state"`
	Round            int32              `json:"round"`
	Turn             int32              `json:"turn"`
	RequestedAbort   bool               `json:"requested_abort"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type CreateGameBugReportRow struct {
	ID               string             `json:"id"`
	RoomCode         string             `json:"room_code"`
	ReporterPlayerID string             `json:"reporter_player_id"`
	ReporterUserID   pgtype.UUID        `json:"reporter_user_id"`
	Description      string             `json:"description"`
	GameState        []byte             `json:"game_state"`
	Round            int32              `json:"round"`
	Turn             int32              `json:"turn"`
	RequestedAbort   bool               `json:"requested_abort"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateGameBugReport(ctx context.Context, arg CreateGameBugReportParams) (CreateGameBugReportRow, error) {
	row := q.db.QueryRow(ctx, createGameBugReport,
		arg.ID,
		arg.RoomCode,
		arg.ReporterPlayerID,
		arg.ReporterUserID,
		arg.Description,
		arg.GameState,
		arg.Round,
		arg.Turn,
		arg.RequestedAbort,
		arg.CreatedAt,
	)
	var i CreateGameBugReportRow
	err := row.Scan(
		&i.ID,
		&i.RoomCode,
		&i.ReporterPlayerID,
		&i.ReporterUserID,
		&i.Description,
		&i.GameState,
		&i.Round,
		&i.Turn,
		&i.RequestedAbort,
		&i.CreatedAt,
	)
	return i, err
}

const getGameBugReport = `-- name: GetGameBugReport :one
SELECT
    id::text AS id,
    room_code,
    reporter_player_id,
    reporter_user_id,
    description,
    game_state,
    round,
    turn,
    requested_abort,
    created_at
FROM game_bug_reports
WHERE id = $1::uuid
  AND completed_at IS NULL
`

type GetGameBugReportRow struct {
	ID               string             `json:"id"`
	RoomCode         string             `json:"room_code"`
	ReporterPlayerID string             `json:"reporter_player_id"`
	ReporterUserID   pgtype.UUID        `json:"reporter_user_id"`
	Description      string             `json:"description"`
	GameState        []byte             `json:"game_state"`
	Round            int32              `json:"round"`
	Turn             int32              `json:"turn"`
	RequestedAbort   bool               `json:"requested_abort"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetGameBugReport(ctx context.Context, id pgtype.UUID) (GetGameBugReportRow, error) {
	row := q.db.QueryRow(ctx, getGameBugReport, id)
	var i GetGameBugReportRow
	err := row.Scan(
		&i.ID,
		&i.RoomCode,
		&i.ReporterPlayerID,
		&i.ReporterUserID,
		&i.Description,
		&i.GameState,
		&i.Round,
		&i.Turn,
		&i.RequestedAbort,
		&i.CreatedAt,
	)
	return i, err
}

const listGameBugReports = `-- name: ListGameBugReports :many
SELECT
    id::text AS id,
    room_code,
    reporter_player_id,
    reporter_user_id,
    description,
    game_state,
    round,
    turn,
    requested_abort,
    created_at
FROM game_bug_reports
WHERE completed_at IS NULL
ORDER BY created_at DESC
LIMIT $1
`

type ListGameBugReportsRow struct {
	ID               string             `json:"id"`
	RoomCode         string             `json:"room_code"`
	ReporterPlayerID string             `json:"reporter_player_id"`
	ReporterUserID   pgtype.UUID        `json:"reporter_user_id"`
	Description      string             `json:"description"`
	GameState        []byte             `json:"game_state"`
	Round            int32              `json:"round"`
	Turn             int32              `json:"turn"`
	RequestedAbort   bool               `json:"requested_abort"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListGameBugReports(ctx context.Context, resultLimit int32) ([]ListGameBugReportsRow, error) {
	rows, err := q.db.Query(ctx, listGameBugReports, resultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGameBugReportsRow
	for rows.Next() {
		var i ListGameBugReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomCode,
			&i.ReporterPlayerID,
			&i.ReporterUserID,
			&i.Description,
			&i.GameState,
			&i.Round,
			&i.Turn,
			&i.RequestedAbort,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameBugReportsPage = `-- name: ListGameBugReportsPage :many
SELECT
    id::text AS id,
    room_code,
    reporter_player_id,
    description,
    round,
    turn,
    requested_abort,
    created_at
FROM game_bug_reports
WHERE completed_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT $2
OFFSET $1
`

type ListGameBugReportsPageParams struct {
	ResultOffset int32 `json:"result_offset"`
	ResultLimit  int32 `json:"result_limit"`
}

type ListGameBugReportsPageRow struct {
	ID               string             `json:"id"`
	RoomCode         string             `json:"room_code"`
	ReporterPlayerID string             `json:"reporter_player_id"`
	Description      string             `json:"description"`
	Round            int32              `json:"round"`
	Turn             int32              `json:"turn"`
	RequestedAbort   bool               `json:"requested_abort"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListGameBugReportsPage(ctx context.Context, arg ListGameBugReportsPageParams) ([]ListGameBugReportsPageRow, error) {
	rows, err := q.db.Query(ctx, listGameBugReportsPage, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGameBugReportsPageRow
	for rows.Next() {
		var i ListGameBugReportsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomCode,
			&i.ReporterPlayerID,
			&i.Description,
			&i.Round,
			&i.Turn,
			&i.RequestedAbort,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
