// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
	ImageUrl  string             `json:"image_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
